name: Environment

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  code_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          linter: jetbrains/qodana-jvm
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          publish_branch: gh-pages
          destination_dir: ./qodana